"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {useParams} from "next/navigation";
import {AlertTriangle,CalendarPlus,ClipboardPlus,Download,Edit3,MessageCircle,Paperclip,Pill,Printer,Upload} from "lucide-react";
import {api,apiUrl} from "@/lib/api";
import {useApi} from "@/lib/hooks";
import {useAuth} from "@/lib/auth";
import type {Patient} from "@/lib/types";
import {dateTime,money,shortDate,titleCase} from "@/lib/utils";
import {PageHeader} from "@/components/ui/page-header";
import {Card,CardHeader} from "@/components/ui/card";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {DataTable} from "@/components/ui/data-table";
import {ErrorMessage,Loading} from "@/components/ui/feedback";
import {EmptyState} from "@/components/ui/empty-state";
import {Modal} from "@/components/ui/modal";
import {Field,Input,Textarea} from "@/components/ui/input";
import {Select} from "@/components/ui/select";
import {PatientForm} from "@/components/forms/patient-form";
import {VisitForm} from "@/components/forms/visit-form";
import {PrescriptionForm} from "@/components/forms/prescription-form";

type Detail={patient:Patient;appointments:any[];visits:any[];prescriptions:any[];invoices:any[];claims:any[];messages:any[];orders:any[];referrals:any[];consents:any[];documents:any[];dispensing:any[]};
const tabs=["Timeline","Appointments","Prescriptions","Orders","Billing","Messages","Documents"];

export default function PatientDetail(){
  const {id}=useParams<{id:string}>();const {user}=useAuth();const {data,loading,error,reload}=useApi<Detail>(`/patients/${id}`);
  const [tab,setTab]=useState("Timeline");const [edit,setEdit]=useState(false);const [visit,setVisit]=useState(false);const [rxVisit,setRxVisit]=useState<number|null>(null);const [notice,setNotice]=useState("");
  if(loading)return <Loading/>;if(!data)return <ErrorMessage message={error}/>;const p=data.patient;const clinical=user?.role==="owner"||user?.role==="doctor";
  async function sendRx(rx:any){await api("/messages",{method:"POST",body:JSON.stringify({patient_id:p.id,prescription_id:rx.id,kind:"prescription"})});setNotice("Prescription message stored in the clearly marked mock delivery log.");reload()}
  return <><PageHeader title={p.full_name} description={`${p.patient_number||`Patient #${p.id}`} · ${p.phone}`} actions={<><Button variant="secondary" onClick={()=>setEdit(true)}><Edit3 size={16}/>Edit demographics</Button><Link href={`/appointments/new?patient=${p.id}`} className="inline-flex h-10 items-center gap-2 rounded-[4px] bg-[#167d78] px-4 text-sm font-semibold text-white"><CalendarPlus size={16}/>Book appointment</Link></>}/>
    {notice&&<div role="status" className="mb-4 border-l-4 border-[#267a52] bg-[#f0f8f3] px-4 py-3 text-sm text-[#315c46]">{notice}</div>}
    <section aria-label="Patient safety header" className={`mb-5 grid gap-3 border px-4 py-3 sm:grid-cols-2 lg:grid-cols-5 ${p.allergies?"safety-stripe border-[#e6c2bd] bg-[#fff4f2]":"border-[#d6e1de] bg-white"}`}>
      <Safety label="Identity" value={p.patient_number||`#${p.id}`}/><Safety label="Date of birth" value={p.date_of_birth?shortDate(p.date_of_birth):"Not recorded"}/><Safety label="Phone" value={p.phone}/><Safety label="Allergies" value={p.allergies||"None recorded"} danger={Boolean(p.allergies)}/><Safety label="Warnings" value={p.chronic_conditions||"None recorded"}/>
    </section>
    <div className="grid gap-5 xl:grid-cols-[300px_1fr]"><aside className="space-y-5"><Card><CardHeader title="Patient identity"/><dl className="grid grid-cols-2 gap-4 p-5 text-sm">{[["CPR",p.cpr_number||"—"],["Preferred name",p.preferred_name||"—"],["Arabic name",p.arabic_name||"—"],["Gender",titleCase(p.gender||"—")],["Nationality",p.nationality||"—"],["Language",p.preferred_language?titleCase(p.preferred_language):"—"],["Emergency contact",p.emergency_contact_name||"—"],["Emergency phone",p.emergency_contact_phone||"—"]].map(([label,value])=><div key={label}><dt className="text-[10px] font-semibold uppercase tracking-wide text-[#52656e]">{label}</dt><dd className="mt-1 font-medium text-[#314854]">{value}</dd></div>)}</dl></Card><Card><CardHeader title="Clinical summary"/><dl className="space-y-4 p-5 text-sm">{[["Allergies",p.allergies||"None recorded"],["Chronic conditions",p.chronic_conditions||"None recorded"],["Current medications",p.current_medications||"None recorded"],["Treatment consent",titleCase(p.treatment_consent_state||"not recorded")],["Notes",p.notes||"None recorded"]].map(([label,value])=><div key={label}><dt className="text-[10px] font-semibold uppercase tracking-wide text-[#52656e]">{label}</dt><dd className="mt-1 leading-5 text-[#314854]">{value}</dd></div>)}</dl></Card></aside>
      <Card><div className="scrollbar flex overflow-x-auto border-b border-[#d6e1de] px-2" role="tablist" aria-label="Patient record sections">{tabs.map(item=><button role="tab" aria-selected={tab===item} key={item} onClick={()=>setTab(item)} className={`whitespace-nowrap border-b-2 px-4 py-3.5 text-sm font-semibold ${tab===item?"border-[#167d78] text-[#0f625f]":"border-transparent text-[#52656e] hover:text-[#314854]"}`}>{item}</button>)}</div><div className="p-4 sm:p-5">
        {tab==="Timeline"&&<Timeline visits={data.visits} dispensing={data.dispensing} clinical={clinical} add={()=>setVisit(true)} prescribe={visitId=>setRxVisit(visitId)}/>} 
        {tab==="Appointments"&&<DataTable rows={data.appointments} keyOf={item=>item.id} columns={[{key:"date",header:"Date",render:item=><Link className="font-semibold text-[#164e67]" href={`/appointments/${item.id}`}>{dateTime(item.start_time)}</Link>},{key:"doctor",header:"Doctor",render:item=>item.doctor_name},{key:"service",header:"Service",render:item=>item.service_name},{key:"status",header:"Status",render:item=><Badge value={item.status}/>}]} />}
        {tab==="Prescriptions"&&<PrescriptionList rows={data.prescriptions} send={sendRx}/>} 
        {tab==="Orders"&&<Orders orders={data.orders} referrals={data.referrals}/>} 
        {tab==="Billing"&&<Billing invoices={data.invoices} claims={data.claims}/>} 
        {tab==="Messages"&&<Messages rows={data.messages}/>} 
        {tab==="Documents"&&<Documents patient={p} rows={data.documents} reload={reload}/>} 
      </div></Card>
    </div>
    <Modal open={edit} onClose={()=>setEdit(false)} title="Edit patient demographics"><div className="p-5"><PatientForm patient={p} onCancel={()=>setEdit(false)} onSaved={()=>{setEdit(false);reload()}}/></div></Modal>
    <Modal open={visit} onClose={()=>setVisit(false)} title="Clinical encounter"><VisitForm patientId={p.id} onCancel={()=>setVisit(false)} onSaved={()=>{setVisit(false);reload()}}/></Modal>
    <Modal open={rxVisit!==null} onClose={()=>setRxVisit(null)} title="New prescription"><PrescriptionForm patientId={p.id} visitId={rxVisit||0} onCancel={()=>setRxVisit(null)} onSaved={()=>{setRxVisit(null);setTab("Prescriptions");reload()}}/></Modal>
  </>;
}

function Safety({label,value,danger}:{label:string;value:string;danger?:boolean}){return <div><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#52656e]">{label}</p><p className={`mt-1 text-sm font-semibold ${danger?"text-[#b74242]":"text-[#163c52]"}`}>{danger&&<AlertTriangle className="mr-1 inline" size={14}/>} {value}</p></div>}
function Timeline({visits,dispensing,clinical,add,prescribe}:{visits:any[];dispensing:any[];clinical:boolean;add:()=>void;prescribe:(id:number)=>void}){return <div>{clinical&&<div className="mb-5 flex justify-end"><Button onClick={add}><ClipboardPlus size={16}/>New encounter</Button></div>}{visits.length?<div className="relative space-y-4 before:absolute before:bottom-0 before:left-[7px] before:top-2 before:w-px before:bg-[#cbdad6]">{visits.map(visit=><div className="relative pl-8" key={visit.id}><span className="absolute left-0 top-1.5 h-[15px] w-[15px] rounded-full border-4 border-white bg-[#167d78] ring-1 ring-[#b9cbc6]"/><div className="border border-[#d6e1de] p-4"><div className="flex flex-wrap justify-between gap-2"><div><div className="flex items-center gap-2"><Link href={`/encounters/${visit.id}`} className="font-semibold text-[#164e67] hover:underline">{visit.diagnosis}</Link><Badge value={visit.status||"finalized"}/></div><p className="mt-1 text-xs text-[#52656e]">{dateTime(visit.created_at)} · {visit.doctor_name}</p></div>{clinical&&<Button variant="secondary" className="h-8" onClick={()=>prescribe(visit.id)}><Pill size={15}/>Prescribe</Button>}</div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Note label="Subjective" text={visit.subjective}/><Note label="Objective" text={visit.objective}/><Note label="Assessment" text={visit.assessment}/><Note label="Plan" text={visit.plan}/></div>{visit.follow_up_date&&<Link href={`/appointments/new?patient=${visit.patient_id||""}`} className="mt-3 inline-flex text-xs font-semibold text-[#0f625f]">Follow-up due {shortDate(visit.follow_up_date)}</Link>}</div></div>)}</div>:<EmptyState title="No clinical encounters" description="Draft and finalized encounter records will build this timeline."/>}{dispensing.length>0&&<div className="mt-5 border-t border-[#d6e1de] pt-4"><h3 className="text-sm font-semibold">Pharmacy activity</h3>{dispensing.map(item=><p className="mt-2 text-sm text-[#526973]" key={item.id}>Dispensing #{item.id} · <Badge value={item.status}/> · {item.finalized_at?dateTime(item.finalized_at):"Draft"}</p>)}</div>}</div>}
function Note({label,text}:{label:string;text:string}){return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-[#52656e]">{label}</p><p className="mt-1 leading-5 text-[#314854]">{text||"—"}</p></div>}
function PrescriptionList({rows,send}:{rows:any[];send:(row:any)=>void}){return rows.length?<div className="space-y-3">{rows.map(rx=><div className="border border-[#d6e1de] p-4" key={rx.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">Prescription #{rx.id}</p><p className="text-xs text-[#52656e]">{dateTime(rx.created_at)}</p></div><div className="flex gap-2"><Link href={`/prescriptions/${rx.id}`} className="inline-flex h-9 items-center gap-2 rounded-[4px] border border-[#b9cbc6] px-3 text-sm font-semibold"><Printer size={15}/>Print</Link><Button className="h-9" variant="secondary" onClick={()=>send(rx)}><MessageCircle size={15}/>Mock send</Button></div></div><ul className="mt-3 space-y-2">{rx.items.map((item:any,index:number)=><li className="text-sm text-[#314854]" key={index}><strong>{item.medicine_name}</strong> — {item.dosage}, {item.frequency} for {item.duration}. <span className="text-[#52656e]">{item.instructions}</span></li>)}</ul></div>)}</div>:<EmptyState title="No prescriptions" description="Prescriptions created from encounters appear here."/>}
function Orders({orders,referrals}:{orders:any[];referrals:any[]}){return <div className="space-y-6"><section><h3 className="mb-3 font-semibold">Lab and imaging orders</h3><DataTable rows={orders} keyOf={item=>item.id} columns={[{key:"kind",header:"Type",render:item=>titleCase(item.kind)},{key:"items",header:"Items",render:item=>item.items.join(", ")},{key:"provider",header:"Provider",render:item=>item.provider||"Not assigned"},{key:"status",header:"Status",render:item=><Badge value={item.status}/>}]} /></section><section><h3 className="mb-3 font-semibold">Referrals</h3><DataTable rows={referrals} keyOf={item=>item.id} columns={[{key:"destination",header:"Destination",render:item=>item.destination},{key:"reason",header:"Reason",render:item=>item.reason},{key:"urgency",header:"Urgency",render:item=>titleCase(item.urgency)},{key:"status",header:"Status",render:item=><Badge value={item.status}/>}]} /></section></div>}
function Billing({invoices,claims}:{invoices:any[];claims:any[]}){return <div className="space-y-6"><section><h3 className="mb-3 font-semibold">Invoices</h3><DataTable rows={invoices} keyOf={item=>item.id} columns={[{key:"number",header:"Invoice",render:item=><Link className="font-semibold text-[#164e67]" href={`/billing/invoices/${item.id}`}>{item.invoice_number}</Link>},{key:"date",header:"Date",render:item=>shortDate(item.created_at)},{key:"total",header:"Total",render:item=>money(item.total_amount)},{key:"balance",header:"Balance",render:item=>money(item.balance_due)},{key:"status",header:"Status",render:item=><Badge value={item.payment_status}/>}]} /></section><section><h3 className="mb-3 font-semibold">Insurance claims</h3><DataTable rows={claims} keyOf={item=>item.id} columns={[{key:"company",header:"Insurer",render:item=>item.company},{key:"policy",header:"Policy",render:item=>item.policy_number},{key:"amount",header:"Amount",render:item=>money(item.claim_amount)},{key:"status",header:"Status",render:item=><Badge value={item.status}/>}]} /></section></div>}
function Messages({rows}:{rows:any[]}){return rows.length?<div className="space-y-3">{rows.map(item=><div key={item.id} className="border border-[#d6e1de] p-4"><div className="flex justify-between"><span className="text-sm font-semibold">{titleCase(item.kind)}</span><Badge value={item.status}/></div><p className="mt-2 text-sm leading-6 text-[#314854]" dir={/[\u0600-\u06FF]/.test(item.body)?"rtl":"ltr"}>{item.body}</p><p className="mt-2 text-xs text-[#52656e]">{dateTime(item.created_at)}</p></div>)}</div>:<EmptyState title="No messages"/>}
function Documents({patient,rows,reload}:{patient:Patient;rows:any[];reload:()=>void}){const [file,setFile]=useState<File|null>(null);const [category,setCategory]=useState("report");const [description,setDescription]=useState("");const [consent,setConsent]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function upload(event:FormEvent){event.preventDefault();if(!file)return;setBusy(true);setError("");const body=new FormData();body.set("patient_id",String(patient.id));body.set("category",category);body.set("description",description);body.set("clinical_photo_consent",String(consent));body.set("file",file);try{await api("/documents",{method:"POST",body});setFile(null);setDescription("");reload()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setBusy(false)}}async function download(id:number){const result=await api<{url:string}>(`/documents/${id}/download-link`,{method:"POST"});window.open(apiUrl(result.url),"_blank","noopener,noreferrer")}return <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div><DataTable rows={rows} keyOf={item=>item.id} empty="No private documents" columns={[{key:"file",header:"Document",render:item=><div><p className="font-semibold">{item.original_name}</p><p className="text-xs text-[#52656e]">{titleCase(item.category)} · {(item.size_bytes/1024).toFixed(1)} KB</p></div>},{key:"date",header:"Uploaded",render:item=>dateTime(item.created_at)},{key:"action",header:"Secure access",render:item=><Button className="h-8 px-2" variant="secondary" onClick={()=>download(item.id)}><Download size={14}/>5-minute link</Button>}]} /></div><form onSubmit={upload} className="space-y-4 border border-[#d6e1de] bg-[#f8faf9] p-4"><h3 className="font-semibold">Private upload</h3><ErrorMessage message={error}/><Field label="Category"><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="report">Report</option><option value="lab_result">Lab result</option><option value="referral">Referral</option><option value="consent">Signed consent</option><option value="clinical_photo">Clinical photo</option></Select></Field><Field label="PDF, JPEG or PNG" required><Input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]||null)} required/></Field><Field label="Description"><Textarea value={description} onChange={e=>setDescription(e.target.value)}/></Field>{category==="clinical_photo"&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/>Clinical-photo consent is recorded.</label>}<Button className="w-full" disabled={busy||!file}><Upload size={15}/>{busy?"Uploading…":"Upload privately"}</Button><p className="text-xs text-[#52656e]"><Paperclip className="mr-1 inline" size={12}/>Files are not published at stable public URLs.</p></form></div>}
